CREATE DATABASE IF NOT EXISTS streetshoot
DEFAULT CHARACTER SET utf8mb4
DEFAULT COLLATE utf8mb4_unicode_ci;

USE streetshoot;

CREATE TABLE IF NOT EXISTS ZONA (
  zona_id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL,
  ciudad VARCHAR(100) NOT NULL,
  tipo ENUM('parque','campo','plaza') NOT NULL,
  lat DECIMAL(9,6) NOT NULL,
  lng DECIMAL(9,6) NOT NULL,
  radio_metros INT NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS USUARIO (
  user_id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(150) NOT NULL UNIQUE,
  nick VARCHAR(50) NOT NULL UNIQUE,
  hash_password VARCHAR(255) NOT NULL,
  nivel INT NOT NULL DEFAULT 1,
  exp INT NOT NULL DEFAULT 0,
  fecha_alta DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  zona_activa_id INT NULL,
  FOREIGN KEY (zona_activa_id) REFERENCES ZONA(zona_id)
    ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS STREETSPOT (
  spot_id INT AUTO_INCREMENT PRIMARY KEY,
  zona_id INT NOT NULL,
  nombre VARCHAR(100) NOT NULL,
  lat DECIMAL(9,6) NOT NULL,
  lng DECIMAL(9,6) NOT NULL,
  radio_metros INT NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  FOREIGN KEY (zona_id) REFERENCES ZONA(zona_id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS RETO (
  reto_id INT AUTO_INCREMENT PRIMARY KEY,
  retador_id INT NOT NULL,
  rival_id INT NOT NULL,
  zona_id INT NOT NULL,
  modo ENUM('sincrono','asincrono') NOT NULL,
  estado ENUM('pendiente','aceptado','jugado','cancelado') NOT NULL,
  fecha_hora DATETIME NOT NULL,
  FOREIGN KEY (retador_id) REFERENCES USUARIO(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (rival_id) REFERENCES USUARIO(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE,
  FOREIGN KEY (zona_id) REFERENCES ZONA(zona_id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS NOTIFICACION (
  notificacion_id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NOT NULL,
  tipo VARCHAR(50) NOT NULL,
  payload TEXT,
  leida BOOLEAN NOT NULL DEFAULT FALSE,
  enviada BOOLEAN NOT NULL DEFAULT FALSE,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (usuario_id) REFERENCES USUARIO(user_id)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;